// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vatesfr/xenorchestra-go-sdk/client (interfaces: XOClient)
//
// Generated by this command:
//
//	mockgen -destination=mock_v1client.go -package=controller -self_package=github.com/vatesfr/cluster-api-provider-vates/internal/controller github.com/vatesfr/xenorchestra-go-sdk/client XOClient
//

// Package controller is a generated GoMock package.
package controller

import (
	reflect "reflect"
	time "time"

	client "github.com/vatesfr/xenorchestra-go-sdk/client"
	gomock "go.uber.org/mock/gomock"
)

// MockXOClient is a mock of XOClient interface.
type MockXOClient struct {
	ctrl     *gomock.Controller
	recorder *MockXOClientMockRecorder
	isgomock struct{}
}

// MockXOClientMockRecorder is the mock recorder for MockXOClient.
type MockXOClientMockRecorder struct {
	mock *MockXOClient
}

// NewMockXOClient creates a new mock instance.
func NewMockXOClient(ctrl *gomock.Controller) *MockXOClient {
	mock := &MockXOClient{ctrl: ctrl}
	mock.recorder = &MockXOClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockXOClient) EXPECT() *MockXOClientMockRecorder {
	return m.recorder
}

// AddResourceSetLimit mocks base method.
func (m *MockXOClient) AddResourceSetLimit(rsReq client.ResourceSet, limit string, quantity int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddResourceSetLimit", rsReq, limit, quantity)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddResourceSetLimit indicates an expected call of AddResourceSetLimit.
func (mr *MockXOClientMockRecorder) AddResourceSetLimit(rsReq, limit, quantity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddResourceSetLimit", reflect.TypeOf((*MockXOClient)(nil).AddResourceSetLimit), rsReq, limit, quantity)
}

// AddResourceSetObject mocks base method.
func (m *MockXOClient) AddResourceSetObject(rsReq client.ResourceSet, object string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddResourceSetObject", rsReq, object)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddResourceSetObject indicates an expected call of AddResourceSetObject.
func (mr *MockXOClientMockRecorder) AddResourceSetObject(rsReq, object any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddResourceSetObject", reflect.TypeOf((*MockXOClient)(nil).AddResourceSetObject), rsReq, object)
}

// AddResourceSetSubject mocks base method.
func (m *MockXOClient) AddResourceSetSubject(rsReq client.ResourceSet, subject string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddResourceSetSubject", rsReq, subject)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddResourceSetSubject indicates an expected call of AddResourceSetSubject.
func (mr *MockXOClientMockRecorder) AddResourceSetSubject(rsReq, subject any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddResourceSetSubject", reflect.TypeOf((*MockXOClient)(nil).AddResourceSetSubject), rsReq, subject)
}

// AddTag mocks base method.
func (m *MockXOClient) AddTag(id, tag string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTag", id, tag)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTag indicates an expected call of AddTag.
func (mr *MockXOClientMockRecorder) AddTag(id, tag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTag", reflect.TypeOf((*MockXOClient)(nil).AddTag), id, tag)
}

// ConnectDisk mocks base method.
func (m *MockXOClient) ConnectDisk(d client.Disk) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConnectDisk", d)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConnectDisk indicates an expected call of ConnectDisk.
func (mr *MockXOClientMockRecorder) ConnectDisk(d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConnectDisk", reflect.TypeOf((*MockXOClient)(nil).ConnectDisk), d)
}

// ConnectVIF mocks base method.
func (m *MockXOClient) ConnectVIF(vifReq *client.VIF) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConnectVIF", vifReq)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConnectVIF indicates an expected call of ConnectVIF.
func (mr *MockXOClientMockRecorder) ConnectVIF(vifReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConnectVIF", reflect.TypeOf((*MockXOClient)(nil).ConnectVIF), vifReq)
}

// CreateAcl mocks base method.
func (m *MockXOClient) CreateAcl(acl client.Acl) (*client.Acl, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAcl", acl)
	ret0, _ := ret[0].(*client.Acl)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAcl indicates an expected call of CreateAcl.
func (mr *MockXOClientMockRecorder) CreateAcl(acl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAcl", reflect.TypeOf((*MockXOClient)(nil).CreateAcl), acl)
}

// CreateBondedNetwork mocks base method.
func (m *MockXOClient) CreateBondedNetwork(netReq client.CreateBondedNetworkRequest) (*client.Network, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBondedNetwork", netReq)
	ret0, _ := ret[0].(*client.Network)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBondedNetwork indicates an expected call of CreateBondedNetwork.
func (mr *MockXOClientMockRecorder) CreateBondedNetwork(netReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBondedNetwork", reflect.TypeOf((*MockXOClient)(nil).CreateBondedNetwork), netReq)
}

// CreateCloudConfig mocks base method.
func (m *MockXOClient) CreateCloudConfig(name, template string) (*client.CloudConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCloudConfig", name, template)
	ret0, _ := ret[0].(*client.CloudConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCloudConfig indicates an expected call of CreateCloudConfig.
func (mr *MockXOClientMockRecorder) CreateCloudConfig(name, template any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCloudConfig", reflect.TypeOf((*MockXOClient)(nil).CreateCloudConfig), name, template)
}

// CreateDisk mocks base method.
func (m *MockXOClient) CreateDisk(vm client.Vm, d client.Disk) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDisk", vm, d)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDisk indicates an expected call of CreateDisk.
func (mr *MockXOClientMockRecorder) CreateDisk(vm, d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDisk", reflect.TypeOf((*MockXOClient)(nil).CreateDisk), vm, d)
}

// CreateNetwork mocks base method.
func (m *MockXOClient) CreateNetwork(netReq client.CreateNetworkRequest) (*client.Network, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNetwork", netReq)
	ret0, _ := ret[0].(*client.Network)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNetwork indicates an expected call of CreateNetwork.
func (mr *MockXOClientMockRecorder) CreateNetwork(netReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNetwork", reflect.TypeOf((*MockXOClient)(nil).CreateNetwork), netReq)
}

// CreateResourceSet mocks base method.
func (m *MockXOClient) CreateResourceSet(rsReq client.ResourceSet) (*client.ResourceSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateResourceSet", rsReq)
	ret0, _ := ret[0].(*client.ResourceSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateResourceSet indicates an expected call of CreateResourceSet.
func (mr *MockXOClientMockRecorder) CreateResourceSet(rsReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateResourceSet", reflect.TypeOf((*MockXOClient)(nil).CreateResourceSet), rsReq)
}

// CreateUser mocks base method.
func (m *MockXOClient) CreateUser(user client.User) (*client.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", user)
	ret0, _ := ret[0].(*client.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockXOClientMockRecorder) CreateUser(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockXOClient)(nil).CreateUser), user)
}

// CreateVDI mocks base method.
func (m *MockXOClient) CreateVDI(vdiReq client.CreateVDIReq) (client.VDI, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVDI", vdiReq)
	ret0, _ := ret[0].(client.VDI)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVDI indicates an expected call of CreateVDI.
func (mr *MockXOClientMockRecorder) CreateVDI(vdiReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVDI", reflect.TypeOf((*MockXOClient)(nil).CreateVDI), vdiReq)
}

// CreateVIF mocks base method.
func (m *MockXOClient) CreateVIF(vm *client.Vm, vif *client.VIF) (*client.VIF, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVIF", vm, vif)
	ret0, _ := ret[0].(*client.VIF)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVIF indicates an expected call of CreateVIF.
func (mr *MockXOClientMockRecorder) CreateVIF(vm, vif any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVIF", reflect.TypeOf((*MockXOClient)(nil).CreateVIF), vm, vif)
}

// CreateVm mocks base method.
func (m *MockXOClient) CreateVm(vmReq client.Vm, d time.Duration) (*client.Vm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVm", vmReq, d)
	ret0, _ := ret[0].(*client.Vm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVm indicates an expected call of CreateVm.
func (mr *MockXOClientMockRecorder) CreateVm(vmReq, d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVm", reflect.TypeOf((*MockXOClient)(nil).CreateVm), vmReq, d)
}

// DeleteAcl mocks base method.
func (m *MockXOClient) DeleteAcl(acl client.Acl) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAcl", acl)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAcl indicates an expected call of DeleteAcl.
func (mr *MockXOClientMockRecorder) DeleteAcl(acl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAcl", reflect.TypeOf((*MockXOClient)(nil).DeleteAcl), acl)
}

// DeleteCloudConfig mocks base method.
func (m *MockXOClient) DeleteCloudConfig(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCloudConfig", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCloudConfig indicates an expected call of DeleteCloudConfig.
func (mr *MockXOClientMockRecorder) DeleteCloudConfig(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCloudConfig", reflect.TypeOf((*MockXOClient)(nil).DeleteCloudConfig), id)
}

// DeleteDisk mocks base method.
func (m *MockXOClient) DeleteDisk(vm client.Vm, d client.Disk) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDisk", vm, d)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDisk indicates an expected call of DeleteDisk.
func (mr *MockXOClientMockRecorder) DeleteDisk(vm, d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDisk", reflect.TypeOf((*MockXOClient)(nil).DeleteDisk), vm, d)
}

// DeleteNetwork mocks base method.
func (m *MockXOClient) DeleteNetwork(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNetwork", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNetwork indicates an expected call of DeleteNetwork.
func (mr *MockXOClientMockRecorder) DeleteNetwork(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNetwork", reflect.TypeOf((*MockXOClient)(nil).DeleteNetwork), id)
}

// DeleteResourceSet mocks base method.
func (m *MockXOClient) DeleteResourceSet(rsReq client.ResourceSet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteResourceSet", rsReq)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteResourceSet indicates an expected call of DeleteResourceSet.
func (mr *MockXOClientMockRecorder) DeleteResourceSet(rsReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteResourceSet", reflect.TypeOf((*MockXOClient)(nil).DeleteResourceSet), rsReq)
}

// DeleteUser mocks base method.
func (m *MockXOClient) DeleteUser(userReq client.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", userReq)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockXOClientMockRecorder) DeleteUser(userReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockXOClient)(nil).DeleteUser), userReq)
}

// DeleteVDI mocks base method.
func (m *MockXOClient) DeleteVDI(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteVDI", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteVDI indicates an expected call of DeleteVDI.
func (mr *MockXOClientMockRecorder) DeleteVDI(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVDI", reflect.TypeOf((*MockXOClient)(nil).DeleteVDI), id)
}

// DeleteVIF mocks base method.
func (m *MockXOClient) DeleteVIF(vifReq *client.VIF) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteVIF", vifReq)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteVIF indicates an expected call of DeleteVIF.
func (mr *MockXOClientMockRecorder) DeleteVIF(vifReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVIF", reflect.TypeOf((*MockXOClient)(nil).DeleteVIF), vifReq)
}

// DeleteVm mocks base method.
func (m *MockXOClient) DeleteVm(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteVm", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteVm indicates an expected call of DeleteVm.
func (mr *MockXOClientMockRecorder) DeleteVm(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVm", reflect.TypeOf((*MockXOClient)(nil).DeleteVm), id)
}

// DisconnectDisk mocks base method.
func (m *MockXOClient) DisconnectDisk(d client.Disk) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisconnectDisk", d)
	ret0, _ := ret[0].(error)
	return ret0
}

// DisconnectDisk indicates an expected call of DisconnectDisk.
func (mr *MockXOClientMockRecorder) DisconnectDisk(d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisconnectDisk", reflect.TypeOf((*MockXOClient)(nil).DisconnectDisk), d)
}

// DisconnectVIF mocks base method.
func (m *MockXOClient) DisconnectVIF(vifReq *client.VIF) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisconnectVIF", vifReq)
	ret0, _ := ret[0].(error)
	return ret0
}

// DisconnectVIF indicates an expected call of DisconnectVIF.
func (mr *MockXOClientMockRecorder) DisconnectVIF(vifReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisconnectVIF", reflect.TypeOf((*MockXOClient)(nil).DisconnectVIF), vifReq)
}

// EjectCd mocks base method.
func (m *MockXOClient) EjectCd(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EjectCd", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// EjectCd indicates an expected call of EjectCd.
func (mr *MockXOClientMockRecorder) EjectCd(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EjectCd", reflect.TypeOf((*MockXOClient)(nil).EjectCd), id)
}

// GetAcl mocks base method.
func (m *MockXOClient) GetAcl(aclReq client.Acl) (*client.Acl, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAcl", aclReq)
	ret0, _ := ret[0].(*client.Acl)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAcl indicates an expected call of GetAcl.
func (mr *MockXOClientMockRecorder) GetAcl(aclReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAcl", reflect.TypeOf((*MockXOClient)(nil).GetAcl), aclReq)
}

// GetAllCloudConfigs mocks base method.
func (m *MockXOClient) GetAllCloudConfigs() ([]client.CloudConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllCloudConfigs")
	ret0, _ := ret[0].([]client.CloudConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllCloudConfigs indicates an expected call of GetAllCloudConfigs.
func (mr *MockXOClientMockRecorder) GetAllCloudConfigs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllCloudConfigs", reflect.TypeOf((*MockXOClient)(nil).GetAllCloudConfigs))
}

// GetAllObjectsOfType mocks base method.
func (m *MockXOClient) GetAllObjectsOfType(obj client.XoObject, response any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllObjectsOfType", obj, response)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetAllObjectsOfType indicates an expected call of GetAllObjectsOfType.
func (mr *MockXOClientMockRecorder) GetAllObjectsOfType(obj, response any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllObjectsOfType", reflect.TypeOf((*MockXOClient)(nil).GetAllObjectsOfType), obj, response)
}

// GetAllUsers mocks base method.
func (m *MockXOClient) GetAllUsers() ([]client.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllUsers")
	ret0, _ := ret[0].([]client.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllUsers indicates an expected call of GetAllUsers.
func (mr *MockXOClientMockRecorder) GetAllUsers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllUsers", reflect.TypeOf((*MockXOClient)(nil).GetAllUsers))
}

// GetAllVDIs mocks base method.
func (m *MockXOClient) GetAllVDIs() ([]client.VDI, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllVDIs")
	ret0, _ := ret[0].([]client.VDI)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllVDIs indicates an expected call of GetAllVDIs.
func (mr *MockXOClientMockRecorder) GetAllVDIs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllVDIs", reflect.TypeOf((*MockXOClient)(nil).GetAllVDIs))
}

// GetBond mocks base method.
func (m *MockXOClient) GetBond(bondReq client.Bond) (*client.Bond, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBond", bondReq)
	ret0, _ := ret[0].(*client.Bond)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBond indicates an expected call of GetBond.
func (mr *MockXOClientMockRecorder) GetBond(bondReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBond", reflect.TypeOf((*MockXOClient)(nil).GetBond), bondReq)
}

// GetBonds mocks base method.
func (m *MockXOClient) GetBonds(bondReq client.Bond) ([]client.Bond, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBonds", bondReq)
	ret0, _ := ret[0].([]client.Bond)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBonds indicates an expected call of GetBonds.
func (mr *MockXOClientMockRecorder) GetBonds(bondReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBonds", reflect.TypeOf((*MockXOClient)(nil).GetBonds), bondReq)
}

// GetCdroms mocks base method.
func (m *MockXOClient) GetCdroms(vm *client.Vm) ([]client.Disk, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCdroms", vm)
	ret0, _ := ret[0].([]client.Disk)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCdroms indicates an expected call of GetCdroms.
func (mr *MockXOClientMockRecorder) GetCdroms(vm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCdroms", reflect.TypeOf((*MockXOClient)(nil).GetCdroms), vm)
}

// GetCloudConfig mocks base method.
func (m *MockXOClient) GetCloudConfig(id string) (*client.CloudConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCloudConfig", id)
	ret0, _ := ret[0].(*client.CloudConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCloudConfig indicates an expected call of GetCloudConfig.
func (mr *MockXOClientMockRecorder) GetCloudConfig(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCloudConfig", reflect.TypeOf((*MockXOClient)(nil).GetCloudConfig), id)
}

// GetCloudConfigByName mocks base method.
func (m *MockXOClient) GetCloudConfigByName(name string) ([]client.CloudConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCloudConfigByName", name)
	ret0, _ := ret[0].([]client.CloudConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCloudConfigByName indicates an expected call of GetCloudConfigByName.
func (mr *MockXOClientMockRecorder) GetCloudConfigByName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCloudConfigByName", reflect.TypeOf((*MockXOClient)(nil).GetCloudConfigByName), name)
}

// GetCurrentUser mocks base method.
func (m *MockXOClient) GetCurrentUser() (*client.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentUser")
	ret0, _ := ret[0].(*client.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentUser indicates an expected call of GetCurrentUser.
func (mr *MockXOClientMockRecorder) GetCurrentUser() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentUser", reflect.TypeOf((*MockXOClient)(nil).GetCurrentUser))
}

// GetDisks mocks base method.
func (m *MockXOClient) GetDisks(vm *client.Vm) ([]client.Disk, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDisks", vm)
	ret0, _ := ret[0].([]client.Disk)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDisks indicates an expected call of GetDisks.
func (mr *MockXOClientMockRecorder) GetDisks(vm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDisks", reflect.TypeOf((*MockXOClient)(nil).GetDisks), vm)
}

// GetHostById mocks base method.
func (m *MockXOClient) GetHostById(id string) (client.Host, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHostById", id)
	ret0, _ := ret[0].(client.Host)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHostById indicates an expected call of GetHostById.
func (mr *MockXOClientMockRecorder) GetHostById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHostById", reflect.TypeOf((*MockXOClient)(nil).GetHostById), id)
}

// GetHostByName mocks base method.
func (m *MockXOClient) GetHostByName(nameLabel string) ([]client.Host, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHostByName", nameLabel)
	ret0, _ := ret[0].([]client.Host)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHostByName indicates an expected call of GetHostByName.
func (mr *MockXOClientMockRecorder) GetHostByName(nameLabel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHostByName", reflect.TypeOf((*MockXOClient)(nil).GetHostByName), nameLabel)
}

// GetNetwork mocks base method.
func (m *MockXOClient) GetNetwork(netReq client.Network) (*client.Network, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNetwork", netReq)
	ret0, _ := ret[0].(*client.Network)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNetwork indicates an expected call of GetNetwork.
func (mr *MockXOClientMockRecorder) GetNetwork(netReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNetwork", reflect.TypeOf((*MockXOClient)(nil).GetNetwork), netReq)
}

// GetNetworks mocks base method.
func (m *MockXOClient) GetNetworks() ([]client.Network, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNetworks")
	ret0, _ := ret[0].([]client.Network)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNetworks indicates an expected call of GetNetworks.
func (mr *MockXOClientMockRecorder) GetNetworks() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNetworks", reflect.TypeOf((*MockXOClient)(nil).GetNetworks))
}

// GetObjectsWithTags mocks base method.
func (m *MockXOClient) GetObjectsWithTags(tags []string) ([]client.Object, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObjectsWithTags", tags)
	ret0, _ := ret[0].([]client.Object)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObjectsWithTags indicates an expected call of GetObjectsWithTags.
func (mr *MockXOClientMockRecorder) GetObjectsWithTags(tags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjectsWithTags", reflect.TypeOf((*MockXOClient)(nil).GetObjectsWithTags), tags)
}

// GetPIF mocks base method.
func (m *MockXOClient) GetPIF(pifReq client.PIF) ([]client.PIF, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPIF", pifReq)
	ret0, _ := ret[0].([]client.PIF)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPIF indicates an expected call of GetPIF.
func (mr *MockXOClientMockRecorder) GetPIF(pifReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPIF", reflect.TypeOf((*MockXOClient)(nil).GetPIF), pifReq)
}

// GetPIFByDevice mocks base method.
func (m *MockXOClient) GetPIFByDevice(dev string, vlan int) ([]client.PIF, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPIFByDevice", dev, vlan)
	ret0, _ := ret[0].([]client.PIF)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPIFByDevice indicates an expected call of GetPIFByDevice.
func (mr *MockXOClientMockRecorder) GetPIFByDevice(dev, vlan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPIFByDevice", reflect.TypeOf((*MockXOClient)(nil).GetPIFByDevice), dev, vlan)
}

// GetPoolByName mocks base method.
func (m *MockXOClient) GetPoolByName(name string) ([]client.Pool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPoolByName", name)
	ret0, _ := ret[0].([]client.Pool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPoolByName indicates an expected call of GetPoolByName.
func (mr *MockXOClientMockRecorder) GetPoolByName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPoolByName", reflect.TypeOf((*MockXOClient)(nil).GetPoolByName), name)
}

// GetPools mocks base method.
func (m *MockXOClient) GetPools(pool client.Pool) ([]client.Pool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPools", pool)
	ret0, _ := ret[0].([]client.Pool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPools indicates an expected call of GetPools.
func (mr *MockXOClientMockRecorder) GetPools(pool any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPools", reflect.TypeOf((*MockXOClient)(nil).GetPools), pool)
}

// GetResourceSet mocks base method.
func (m *MockXOClient) GetResourceSet(rsReq client.ResourceSet) ([]client.ResourceSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResourceSet", rsReq)
	ret0, _ := ret[0].([]client.ResourceSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResourceSet indicates an expected call of GetResourceSet.
func (mr *MockXOClientMockRecorder) GetResourceSet(rsReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResourceSet", reflect.TypeOf((*MockXOClient)(nil).GetResourceSet), rsReq)
}

// GetResourceSetById mocks base method.
func (m *MockXOClient) GetResourceSetById(id string) (*client.ResourceSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResourceSetById", id)
	ret0, _ := ret[0].(*client.ResourceSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResourceSetById indicates an expected call of GetResourceSetById.
func (mr *MockXOClientMockRecorder) GetResourceSetById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResourceSetById", reflect.TypeOf((*MockXOClient)(nil).GetResourceSetById), id)
}

// GetResourceSets mocks base method.
func (m *MockXOClient) GetResourceSets() ([]client.ResourceSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResourceSets")
	ret0, _ := ret[0].([]client.ResourceSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResourceSets indicates an expected call of GetResourceSets.
func (mr *MockXOClientMockRecorder) GetResourceSets() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResourceSets", reflect.TypeOf((*MockXOClient)(nil).GetResourceSets))
}

// GetSortedHosts mocks base method.
func (m *MockXOClient) GetSortedHosts(host client.Host, sortBy, sortOrder string) ([]client.Host, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSortedHosts", host, sortBy, sortOrder)
	ret0, _ := ret[0].([]client.Host)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSortedHosts indicates an expected call of GetSortedHosts.
func (mr *MockXOClientMockRecorder) GetSortedHosts(host, sortBy, sortOrder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSortedHosts", reflect.TypeOf((*MockXOClient)(nil).GetSortedHosts), host, sortBy, sortOrder)
}

// GetStorageRepository mocks base method.
func (m *MockXOClient) GetStorageRepository(sr client.StorageRepository) ([]client.StorageRepository, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStorageRepository", sr)
	ret0, _ := ret[0].([]client.StorageRepository)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStorageRepository indicates an expected call of GetStorageRepository.
func (mr *MockXOClientMockRecorder) GetStorageRepository(sr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStorageRepository", reflect.TypeOf((*MockXOClient)(nil).GetStorageRepository), sr)
}

// GetStorageRepositoryById mocks base method.
func (m *MockXOClient) GetStorageRepositoryById(id string) (client.StorageRepository, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStorageRepositoryById", id)
	ret0, _ := ret[0].(client.StorageRepository)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStorageRepositoryById indicates an expected call of GetStorageRepositoryById.
func (mr *MockXOClientMockRecorder) GetStorageRepositoryById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStorageRepositoryById", reflect.TypeOf((*MockXOClient)(nil).GetStorageRepositoryById), id)
}

// GetTemplate mocks base method.
func (m *MockXOClient) GetTemplate(template client.Template) ([]client.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTemplate", template)
	ret0, _ := ret[0].([]client.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTemplate indicates an expected call of GetTemplate.
func (mr *MockXOClientMockRecorder) GetTemplate(template any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTemplate", reflect.TypeOf((*MockXOClient)(nil).GetTemplate), template)
}

// GetUser mocks base method.
func (m *MockXOClient) GetUser(userReq client.User) (*client.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", userReq)
	ret0, _ := ret[0].(*client.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockXOClientMockRecorder) GetUser(userReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockXOClient)(nil).GetUser), userReq)
}

// GetVDI mocks base method.
func (m *MockXOClient) GetVDI(vdiReq client.VDI) (client.VDI, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVDI", vdiReq)
	ret0, _ := ret[0].(client.VDI)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVDI indicates an expected call of GetVDI.
func (mr *MockXOClientMockRecorder) GetVDI(vdiReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVDI", reflect.TypeOf((*MockXOClient)(nil).GetVDI), vdiReq)
}

// GetVDIs mocks base method.
func (m *MockXOClient) GetVDIs(vdiReq client.VDI) ([]client.VDI, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVDIs", vdiReq)
	ret0, _ := ret[0].([]client.VDI)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVDIs indicates an expected call of GetVDIs.
func (mr *MockXOClientMockRecorder) GetVDIs(vdiReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVDIs", reflect.TypeOf((*MockXOClient)(nil).GetVDIs), vdiReq)
}

// GetVIF mocks base method.
func (m *MockXOClient) GetVIF(vifReq *client.VIF) (*client.VIF, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVIF", vifReq)
	ret0, _ := ret[0].(*client.VIF)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVIF indicates an expected call of GetVIF.
func (mr *MockXOClientMockRecorder) GetVIF(vifReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVIF", reflect.TypeOf((*MockXOClient)(nil).GetVIF), vifReq)
}

// GetVIFs mocks base method.
func (m *MockXOClient) GetVIFs(vm *client.Vm) ([]client.VIF, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVIFs", vm)
	ret0, _ := ret[0].([]client.VIF)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVIFs indicates an expected call of GetVIFs.
func (mr *MockXOClientMockRecorder) GetVIFs(vm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVIFs", reflect.TypeOf((*MockXOClient)(nil).GetVIFs), vm)
}

// GetVm mocks base method.
func (m *MockXOClient) GetVm(vmReq client.Vm) (*client.Vm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVm", vmReq)
	ret0, _ := ret[0].(*client.Vm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVm indicates an expected call of GetVm.
func (mr *MockXOClientMockRecorder) GetVm(vmReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVm", reflect.TypeOf((*MockXOClient)(nil).GetVm), vmReq)
}

// GetVms mocks base method.
func (m *MockXOClient) GetVms(vm client.Vm) ([]client.Vm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVms", vm)
	ret0, _ := ret[0].([]client.Vm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVms indicates an expected call of GetVms.
func (mr *MockXOClientMockRecorder) GetVms(vm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVms", reflect.TypeOf((*MockXOClient)(nil).GetVms), vm)
}

// HaltVm mocks base method.
func (m *MockXOClient) HaltVm(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HaltVm", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// HaltVm indicates an expected call of HaltVm.
func (mr *MockXOClientMockRecorder) HaltVm(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HaltVm", reflect.TypeOf((*MockXOClient)(nil).HaltVm), id)
}

// InsertCd mocks base method.
func (m *MockXOClient) InsertCd(vmId, cdId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertCd", vmId, cdId)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertCd indicates an expected call of InsertCd.
func (mr *MockXOClientMockRecorder) InsertCd(vmId, cdId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertCd", reflect.TypeOf((*MockXOClient)(nil).InsertCd), vmId, cdId)
}

// PauseVm mocks base method.
func (m *MockXOClient) PauseVm(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PauseVm", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// PauseVm indicates an expected call of PauseVm.
func (mr *MockXOClientMockRecorder) PauseVm(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PauseVm", reflect.TypeOf((*MockXOClient)(nil).PauseVm), id)
}

// RemoveResourceSetLimit mocks base method.
func (m *MockXOClient) RemoveResourceSetLimit(rsReq client.ResourceSet, limit string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveResourceSetLimit", rsReq, limit)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveResourceSetLimit indicates an expected call of RemoveResourceSetLimit.
func (mr *MockXOClientMockRecorder) RemoveResourceSetLimit(rsReq, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveResourceSetLimit", reflect.TypeOf((*MockXOClient)(nil).RemoveResourceSetLimit), rsReq, limit)
}

// RemoveResourceSetObject mocks base method.
func (m *MockXOClient) RemoveResourceSetObject(rsReq client.ResourceSet, object string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveResourceSetObject", rsReq, object)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveResourceSetObject indicates an expected call of RemoveResourceSetObject.
func (mr *MockXOClientMockRecorder) RemoveResourceSetObject(rsReq, object any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveResourceSetObject", reflect.TypeOf((*MockXOClient)(nil).RemoveResourceSetObject), rsReq, object)
}

// RemoveResourceSetSubject mocks base method.
func (m *MockXOClient) RemoveResourceSetSubject(rsReq client.ResourceSet, subject string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveResourceSetSubject", rsReq, subject)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveResourceSetSubject indicates an expected call of RemoveResourceSetSubject.
func (mr *MockXOClientMockRecorder) RemoveResourceSetSubject(rsReq, subject any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveResourceSetSubject", reflect.TypeOf((*MockXOClient)(nil).RemoveResourceSetSubject), rsReq, subject)
}

// RemoveTag mocks base method.
func (m *MockXOClient) RemoveTag(id, tag string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveTag", id, tag)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveTag indicates an expected call of RemoveTag.
func (mr *MockXOClientMockRecorder) RemoveTag(id, tag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveTag", reflect.TypeOf((*MockXOClient)(nil).RemoveTag), id, tag)
}

// ResizeVDI mocks base method.
func (m *MockXOClient) ResizeVDI(d client.Disk) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResizeVDI", d)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResizeVDI indicates an expected call of ResizeVDI.
func (mr *MockXOClientMockRecorder) ResizeVDI(d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResizeVDI", reflect.TypeOf((*MockXOClient)(nil).ResizeVDI), d)
}

// StartVm mocks base method.
func (m *MockXOClient) StartVm(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartVm", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartVm indicates an expected call of StartVm.
func (mr *MockXOClientMockRecorder) StartVm(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartVm", reflect.TypeOf((*MockXOClient)(nil).StartVm), id)
}

// SuspendVm mocks base method.
func (m *MockXOClient) SuspendVm(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SuspendVm", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SuspendVm indicates an expected call of SuspendVm.
func (mr *MockXOClientMockRecorder) SuspendVm(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SuspendVm", reflect.TypeOf((*MockXOClient)(nil).SuspendVm), id)
}

// UpdateNetwork mocks base method.
func (m *MockXOClient) UpdateNetwork(netReq client.UpdateNetworkRequest) (*client.Network, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNetwork", netReq)
	ret0, _ := ret[0].(*client.Network)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateNetwork indicates an expected call of UpdateNetwork.
func (mr *MockXOClientMockRecorder) UpdateNetwork(netReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNetwork", reflect.TypeOf((*MockXOClient)(nil).UpdateNetwork), netReq)
}

// UpdateVDI mocks base method.
func (m *MockXOClient) UpdateVDI(d client.Disk) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVDI", d)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateVDI indicates an expected call of UpdateVDI.
func (mr *MockXOClientMockRecorder) UpdateVDI(d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVDI", reflect.TypeOf((*MockXOClient)(nil).UpdateVDI), d)
}

// UpdateVm mocks base method.
func (m *MockXOClient) UpdateVm(vmReq client.Vm) (*client.Vm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVm", vmReq)
	ret0, _ := ret[0].(*client.Vm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateVm indicates an expected call of UpdateVm.
func (mr *MockXOClientMockRecorder) UpdateVm(vmReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVm", reflect.TypeOf((*MockXOClient)(nil).UpdateVm), vmReq)
}
