package controller

import (
	"bytes"
	"context"
	_ "embed"
	"fmt"
	"text/template"
	"time"

	"k8s.io/apimachinery/pkg/runtime"

	corev1 "k8s.io/api/core/v1"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"

	addonsv1 "sigs.k8s.io/cluster-api/api/addons/v1beta2" // ClusterResourceSet

	clusterv1 "sigs.k8s.io/cluster-api/api/core/v1beta2"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/controller/controllerutil"
	"sigs.k8s.io/controller-runtime/pkg/handler"
	"sigs.k8s.io/controller-runtime/pkg/log"
	"sigs.k8s.io/controller-runtime/pkg/reconcile"

	infrastructurev1beta2 "github.com/vatesfr/cluster-api-provider-vates/api/v1beta2"
	xok8scommon "github.com/vatesfr/xenorchestra-k8s-common"
)

const (
	xoClusterFinalizer = "vates.infrastructure.cluster.x-k8s.io/xocluster"
	// defaultNamespace is the namespace used for addon ConfigMaps and
	// ClusterResourceSets.
	defaultNamespace = "default"
)

// XOClusterReconciler reconciles a XOCluster object.
type XOClusterReconciler struct {
	client.Client
	Scheme  *runtime.Scheme
	XoCreds *xok8scommon.XoConfig
}

var _ reconcile.Reconciler = (*XOClusterReconciler)(nil)

// +kubebuilder:rbac:groups=vates.infrastructure.cluster.x-k8s.io,resources=xoclusters,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=vates.infrastructure.cluster.x-k8s.io,resources=xoclusters/status,verbs=get;update;patch
// +kubebuilder:rbac:groups=vates.infrastructure.cluster.x-k8s.io,resources=xoclusters/finalizers,verbs=update
// +kubebuilder:rbac:groups=vates.infrastructure.cluster.x-k8s.io,resources=xoclustertemplates,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=cluster.x-k8s.io,resources=clusters;clusters/status,verbs=get;list;watch;patch;update
// +kubebuilder:rbac:groups=cluster.x-k8s.io,resources=machines;machines/status,verbs=get;list;watch
// +kubebuilder:rbac:groups=core,resources=events,verbs=create;patch
// +kubebuilder:rbac:groups=addons.cluster.x-k8s.io,resources=clusterresourcesets,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups="",resources=configmaps,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups="",resources=secrets,verbs=get;list;watch

func (r *XOClusterReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	xoCluster := &infrastructurev1beta2.XOCluster{}
	if err := r.Get(ctx, req.NamespacedName, xoCluster); err != nil {
		if apierrors.IsNotFound(err) {
			return ctrl.Result{}, nil
		}
		return ctrl.Result{}, err
	}

	if !xoCluster.DeletionTimestamp.IsZero() {
		return r.reconcileDelete(ctx, xoCluster)
	}

	return r.reconcileNormal(ctx, xoCluster)
}

func (r *XOClusterReconciler) reconcileNormal(ctx context.Context, xoCluster *infrastructurev1beta2.XOCluster) (ctrl.Result, error) {
	logger := log.FromContext(ctx)

	if controllerutil.AddFinalizer(xoCluster, xoClusterFinalizer) {
		if err := r.Update(ctx, xoCluster); err != nil {
			logger.Error(err, "Failed to add finalizer")
			return ctrl.Result{}, err
		}
	}

	patchBase := xoCluster.DeepCopy()

	cluster, err := r.getOwnerCluster(ctx, xoCluster)
	if err != nil {
		logger.Error(err, "Failed to get owner Cluster")
		return ctrl.Result{}, err
	}
	if cluster == nil {
		logger.Info("Waiting for owner Cluster to be created")
		return ctrl.Result{}, nil
	}

	// Ensure the owner Cluster carries the standard cluster-name label so that
	// the ClusterResourceSet (CCM/CSI) created below actually matches it. CAPI's
	// addons controller selects clusters by this label; clusters created from
	// flat templates (e.g. Talos) may not have it, leaving the CRS unapplied.
	// This is a no-op for clusters that already have the label (e.g. kubeadm
	// ones generated by clusterctl).
	if err := r.ensureClusterNameLabel(ctx, cluster); err != nil {
		logger.Error(err, "Failed to ensure cluster-name label on owner Cluster")
		return ctrl.Result{}, err
	}

	// -------------------------------------------------------------------------
	// CONTROL PLANE ENDPOINT
	// Priority order:
	// 1. spec.controlPlaneEndpoint (set by user or ClusterClass topology)
	// 2. Discover from a ready control plane XOMachine (backward compat)
	// -------------------------------------------------------------------------
	needsRequeue := false
	if xoCluster.Status.ControlPlaneEndpoint == nil || xoCluster.Status.ControlPlaneEndpoint.Host == "" {
		ep := xoCluster.Spec.ControlPlaneEndpoint
		if ep != nil && ep.Host != "" {
			xoCluster.Status.ControlPlaneEndpoint = ep
			logger.Info("Control plane endpoint set from spec", "host", ep.Host, "port", ep.Port)
		} else {
			endpoint, err := r.discoverControlPlaneEndpoint(ctx, cluster)
			if err != nil {
				logger.Error(err, "Failed to discover control plane endpoint")
				return ctrl.Result{}, err
			}
			if endpoint != nil {
				xoCluster.Status.ControlPlaneEndpoint = endpoint
				logger.Info("Control plane endpoint discovered from machine", "host", endpoint.Host, "port", endpoint.Port)
			} else {
				logger.Info("Waiting for a ready control plane machine to discover endpoint")
				needsRequeue = true
			}
		}
	}

	if !needsRequeue {
		xoCluster.Status.Ready = true
		xoCluster.Status.Initialization = &infrastructurev1beta2.InitializationStatus{Provisioned: true}
		r.setCondition(xoCluster, "Ready", metav1.ConditionTrue, "ClusterInfrastructureReady", "Cluster infrastructure is ready")
	} else {
		r.setCondition(xoCluster, "Ready", metav1.ConditionFalse, "WaitingForControlPlaneEndpoint", "Waiting for a ready control plane machine to discover the endpoint")
	}

	if err := r.Status().Patch(ctx, xoCluster, client.MergeFrom(patchBase)); err != nil {
		logger.Error(err, "Failed to update XOCluster status")
		return ctrl.Result{}, err
	}

	// CAUTION: ControlPlaneEndpoint may be nil if not yet discovered.
	// Only log the host if the endpoint exists to avoid a nil pointer panic.
	if xoCluster.Status.ControlPlaneEndpoint != nil {
		logger.Info("XOCluster reconciled", "name", xoCluster.Name, "endpoint", xoCluster.Status.ControlPlaneEndpoint.Host)
	} else {
		logger.Info("XOCluster reconciled", "name", xoCluster.Name, "endpoint", "not yet discovered")
	}

	// If the endpoint has not been discovered yet, requeue to re-check
	// in 10 seconds (time for the VM to boot and guest tools to report the IP).
	if needsRequeue {
		return ctrl.Result{RequeueAfter: 10 * time.Second}, nil
	}

	// Resolve XO credentials for this cluster (from identityRef or global fallback).
	xoCreds, err := ResolveXOConfig(ctx, r.Client, xoCluster.Namespace, xoCluster.Spec.IdentityRef, r.XoCreds)
	if err != nil {
		logger.Error(err, "Failed to resolve XO credentials")
		r.setCondition(xoCluster, "Ready", metav1.ConditionFalse, "CredentialsResolutionFailed", err.Error())
		return ctrl.Result{}, err
	}

	// Ensure CCM + CSI driver ConfigMaps and ClusterResourceSet exist for
	// automatic deployment into workload clusters.
	if err := r.reconcileAddons(ctx, xoCluster, cluster.Name, xoCreds); err != nil {
		logger.Error(err, "Failed to reconcile addon resources, will retry")
		return ctrl.Result{RequeueAfter: 30 * time.Second}, nil
	}

	return ctrl.Result{}, nil
}

func (r *XOClusterReconciler) reconcileDelete(ctx context.Context, xoCluster *infrastructurev1beta2.XOCluster) (ctrl.Result, error) {
	logger := log.FromContext(ctx)

	if controllerutil.ContainsFinalizer(xoCluster, xoClusterFinalizer) {
		logger.Info("Removing finalizer from XOCluster", "name", xoCluster.Name)

		controllerutil.RemoveFinalizer(xoCluster, xoClusterFinalizer)
		if err := r.Update(ctx, xoCluster); err != nil {
			return ctrl.Result{}, err
		}
	}

	return ctrl.Result{}, nil
}

// ensureClusterNameLabel adds the standard CAPI cluster-name label to the
// owner Cluster when it is missing. The ClusterResourceSet selector relies on
// this label to match the cluster, so clusters created without it (e.g. flat
// Talos templates) would otherwise never get their CCM/CSI applied.
func (r *XOClusterReconciler) ensureClusterNameLabel(ctx context.Context, cluster *clusterv1.Cluster) error {
	logger := log.FromContext(ctx)

	if cluster.Labels[clusterv1.ClusterNameLabel] == cluster.Name {
		return nil
	}

	patchBase := cluster.DeepCopy()
	if cluster.Labels == nil {
		cluster.Labels = map[string]string{}
	}
	cluster.Labels[clusterv1.ClusterNameLabel] = cluster.Name
	if err := r.Patch(ctx, cluster, client.MergeFrom(patchBase)); err != nil {
		if !apierrors.IsConflict(err) {
			logger.Error(err, "Failed to add cluster-name label to Cluster", "cluster", cluster.Name)
			return err
		}
		logger.Info("Conflict adding cluster-name label to Cluster, retrying", "cluster", cluster.Name)
		fresh := &clusterv1.Cluster{}
		if err := r.Get(ctx, types.NamespacedName{Namespace: cluster.Namespace, Name: cluster.Name}, fresh); err != nil {
			return err
		}
		patchBase = fresh.DeepCopy()
		if fresh.Labels == nil {
			fresh.Labels = map[string]string{}
		}
		fresh.Labels[clusterv1.ClusterNameLabel] = fresh.Name
		if err := r.Patch(ctx, fresh, client.MergeFrom(patchBase)); err != nil {
			logger.Error(err, "Failed to add cluster-name label to Cluster after retry", "cluster", fresh.Name)
			return err
		}
	}
	logger.Info("Added cluster-name label to Cluster for CRS matching", "cluster", cluster.Name, "label", clusterv1.ClusterNameLabel)
	return nil
}

func (r *XOClusterReconciler) getOwnerCluster(ctx context.Context, xoCluster *infrastructurev1beta2.XOCluster) (*clusterv1.Cluster, error) {
	var ownerRef *metav1.OwnerReference
	for i := range xoCluster.OwnerReferences {
		ref := &xoCluster.OwnerReferences[i]
		if ref.Kind == "Cluster" && ref.APIVersion == clusterv1.GroupVersion.String() {
			ownerRef = ref
			break
		}
	}
	if ownerRef == nil {
		return nil, nil
	}

	cluster := &clusterv1.Cluster{}
	if err := r.Get(ctx, types.NamespacedName{
		Namespace: xoCluster.Namespace,
		Name:      ownerRef.Name,
	}, cluster); err != nil {
		if apierrors.IsNotFound(err) {
			return nil, nil
		}
		return nil, err
	}

	if cluster.UID != ownerRef.UID {
		return nil, nil
	}
	return cluster, nil
}

func (r *XOClusterReconciler) discoverControlPlaneEndpoint(ctx context.Context, cluster *clusterv1.Cluster) (*infrastructurev1beta2.APIEndpoint, error) {
	machineList := &clusterv1.MachineList{}
	if err := r.List(
		ctx, machineList,
		client.InNamespace(cluster.Namespace),
		client.MatchingLabels{clusterv1.MachineControlPlaneLabel: ""},
	); err != nil {
		return nil, fmt.Errorf("failed to list control plane machines: %w", err)
	}

	for i := range machineList.Items {
		m := &machineList.Items[i]
		if m.Spec.ClusterName != cluster.Name {
			continue
		}

		if m.Spec.InfrastructureRef.Kind != infrastructurev1beta2.KindXOMachine {
			continue
		}

		xoMachine := &infrastructurev1beta2.XOMachine{}
		if err := r.Get(ctx, types.NamespacedName{
			Namespace: m.Namespace,
			Name:      m.Spec.InfrastructureRef.Name,
		}, xoMachine); err != nil {
			continue
		}

		if xoMachine.Status.Ready && len(xoMachine.Status.Addresses) > 0 {
			for _, addr := range xoMachine.Status.Addresses {
				if addr.Type == corev1.NodeInternalIP || addr.Type == corev1.NodeExternalIP {
					return &infrastructurev1beta2.APIEndpoint{
						Host: addr.Address,
						Port: 6443,
					}, nil
				}
			}
		}
	}

	return nil, nil
}

func (r *XOClusterReconciler) SetupWithManager(mgr ctrl.Manager) error {
	return ctrl.NewControllerManagedBy(mgr).
		For(&infrastructurev1beta2.XOCluster{}).
		Watches(
			&clusterv1.Cluster{},
			handler.EnqueueRequestsFromMapFunc(r.clusterToXOCluster),
		).
		Watches(
			&clusterv1.Machine{},
			handler.EnqueueRequestsFromMapFunc(r.machineToXOCluster),
		).
		Named("xocluster").
		Complete(r)
}

// clusterToXOCluster maps a Cluster change to the corresponding XOCluster.
func (r *XOClusterReconciler) clusterToXOCluster(_ context.Context, o client.Object) []reconcile.Request {
	cluster, ok := o.(*clusterv1.Cluster)
	if !ok {
		return nil
	}
	if cluster.Spec.InfrastructureRef.Kind != "XOCluster" {
		return nil
	}
	return []reconcile.Request{{
		NamespacedName: types.NamespacedName{
			Namespace: cluster.Namespace,
			Name:      cluster.Spec.InfrastructureRef.Name,
		},
	}}
}

// machineToXOCluster maps a control plane Machine change to the corresponding
// XOCluster, so that endpoint discovery is re-triggered when a machine becomes Ready.
func (r *XOClusterReconciler) machineToXOCluster(ctx context.Context, o client.Object) []reconcile.Request {
	machine, ok := o.(*clusterv1.Machine)
	if !ok {
		return nil
	}
	if _, ok := machine.Labels[clusterv1.MachineControlPlaneLabel]; !ok {
		return nil
	}
	clusterName, ok := machine.Labels[clusterv1.ClusterNameLabel]
	if !ok {
		return nil
	}
	cluster := &clusterv1.Cluster{}
	if err := r.Get(ctx, types.NamespacedName{Namespace: machine.Namespace, Name: clusterName}, cluster); err != nil {
		return nil
	}
	if cluster.Spec.InfrastructureRef.Kind != "XOCluster" {
		return nil
	}
	return []reconcile.Request{{
		NamespacedName: types.NamespacedName{
			Namespace: cluster.Namespace,
			Name:      cluster.Spec.InfrastructureRef.Name,
		},
	}}
}

// ccmManifestTemplate is the CCM deployment manifest rendered with XO credentials.
//
//go:embed ccm-manifest.yaml
var ccmManifestTemplate string

// csiManifestTemplate is the CSI driver deployment manifest rendered with the
// API server endpoint. It reuses the xenorchestra-cloud-controller-manager
// secret created by the CCM.
//
//go:embed csi-manifest.yaml
var csiManifestTemplate string

// ccmManifestData holds the template values for the CCM manifest.
type ccmManifestData struct {
	XOAURL      string
	XOAToken    string
	XOAInsecure string
}

// csiManifestData holds the template values for the CSI manifest.
type csiManifestData struct {
	ApiServerHost string
	ApiServerPort string
}

// cniCiliumManifest is the rendered Cilium CNI manifest applied via
// ClusterResourceSet when spec.addons.cni == "cilium".
//
//go:embed cni-cilium.yaml
var cniCiliumManifest string

// defaultAddons returns the effective addon selection, filling defaults for
// unset fields (CCM/CSI enabled, no CNI).
func defaultAddons(a *infrastructurev1beta2.AddonsSpec) *infrastructurev1beta2.AddonsSpec {
	if a == nil {
		a = &infrastructurev1beta2.AddonsSpec{}
	}
	if a.CCM == nil {
		enabled := true
		a.CCM = &enabled
	}
	if a.CSI == nil {
		enabled := true
		a.CSI = &enabled
	}
	if a.CNI == nil {
		none := "none"
		a.CNI = &none
	}
	return a
}

// ensureAddon creates/updates the per-cluster ConfigMap holding the rendered
// addon manifest and a ClusterResourceSet targeting only this cluster.
func (r *XOClusterReconciler) ensureAddon(ctx context.Context, clusterName, addon, crsName, cmName, strategy, manifest string) error {
	logger := log.FromContext(ctx)

	cm := &corev1.ConfigMap{ObjectMeta: metav1.ObjectMeta{Name: cmName, Namespace: defaultNamespace}}
	op, err := ctrl.CreateOrUpdate(ctx, r.Client, cm, func() error {
		if cm.Data == nil {
			cm.Data = make(map[string]string)
		}
		cm.Data[addon+".yaml"] = manifest
		return nil
	})
	if err != nil {
		return fmt.Errorf("create/update ConfigMap %s: %w", cmName, err)
	}
	logger.Info("Addon manifests ConfigMap reconciled", "addon", addon, "cluster", clusterName, "configmap", cmName, "operation", op)

	crs := &addonsv1.ClusterResourceSet{ObjectMeta: metav1.ObjectMeta{Name: crsName, Namespace: defaultNamespace}}
	op, err = ctrl.CreateOrUpdate(ctx, r.Client, crs, func() error {
		crs.Spec = addonsv1.ClusterResourceSetSpec{
			ClusterSelector: metav1.LabelSelector{
				MatchLabels: map[string]string{"cluster.x-k8s.io/cluster-name": clusterName},
			},
			Resources: []addonsv1.ResourceRef{{Kind: "ConfigMap", Name: cmName}},
			Strategy:  strategy,
		}
		return nil
	})
	if err != nil {
		return fmt.Errorf("create/update ClusterResourceSet %s: %w", crsName, err)
	}
	logger.Info("Addon ClusterResourceSet reconciled", "addon", addon, "cluster", clusterName, "crs", crsName, "operation", op)
	return nil
}

// removeAddon deletes the per-cluster ConfigMap and ClusterResourceSet of a
// disabled addon. Resources already applied to the workload cluster are left
// untouched.
func (r *XOClusterReconciler) removeAddon(ctx context.Context, clusterName, addon, crsName, cmName string) error {
	logger := log.FromContext(ctx)
	for _, obj := range []client.Object{
		&addonsv1.ClusterResourceSet{ObjectMeta: metav1.ObjectMeta{Name: crsName, Namespace: defaultNamespace}},
		&corev1.ConfigMap{ObjectMeta: metav1.ObjectMeta{Name: cmName, Namespace: defaultNamespace}},
	} {
		if err := r.Delete(ctx, obj); err != nil && !apierrors.IsNotFound(err) {
			return err
		}
	}
	logger.Info("Addon disabled, removed ConfigMap and ClusterResourceSet", "addon", addon, "cluster", clusterName)
	return nil
}

// reconcileAddons creates per-cluster ConfigMaps and one ClusterResourceSet per
// enabled addon (CCM, CSI, CNI), targeting only this cluster. Addons are
// optional and driven by the XOCluster spec.addons field.
func (r *XOClusterReconciler) reconcileAddons(ctx context.Context, xoCluster *infrastructurev1beta2.XOCluster, clusterName string, xoCreds *xok8scommon.XoConfig) error {
	addons := defaultAddons(xoCluster.Spec.Addons)

	// -----------------------------------------------------------------------
	// CCM (Xen Orchestra cloud-controller-manager)
	// -----------------------------------------------------------------------
	ccmCMName := "ccm-manifests-" + clusterName
	if *addons.CCM {
		ccmData := ccmManifestData{
			XOAURL:      xoCreds.URL,
			XOAToken:    xoCreds.Token,
			XOAInsecure: trueStr,
		}
		if xoCreds.Insecure {
			ccmData.XOAInsecure = trueStr
		} else {
			ccmData.XOAInsecure = "false"
		}
		tmpl, err := template.New("ccm").Parse(ccmManifestTemplate)
		if err != nil {
			return fmt.Errorf("parse CCM template: %w", err)
		}
		var ccmBuf bytes.Buffer
		if err := tmpl.Execute(&ccmBuf, ccmData); err != nil {
			return fmt.Errorf("execute CCM template: %w", err)
		}
		if err := r.ensureAddon(ctx, clusterName, "ccm", "ccm-deployment-"+clusterName, ccmCMName, "Reconcile", ccmBuf.String()); err != nil {
			return err
		}
	} else if err := r.removeAddon(ctx, clusterName, "ccm", "ccm-deployment-"+clusterName, ccmCMName); err != nil {
		return err
	}

	// -----------------------------------------------------------------------
	// CSI (Xen Orchestra storage driver)
	// -----------------------------------------------------------------------
	csiCMName := "csi-manifests-" + clusterName
	if *addons.CSI {
		apiServerHost := "127.0.0.1"
		apiServerPort := "6443"
		if xoCluster.Spec.ControlPlaneEndpoint != nil {
			apiServerHost = xoCluster.Spec.ControlPlaneEndpoint.Host
			apiServerPort = fmt.Sprintf("%d", xoCluster.Spec.ControlPlaneEndpoint.Port)
		}
		csiData := csiManifestData{
			ApiServerHost: apiServerHost,
			ApiServerPort: apiServerPort,
		}
		csiTmpl, err := template.New("csi").Parse(csiManifestTemplate)
		if err != nil {
			return fmt.Errorf("parse CSI template: %w", err)
		}
		var csiBuf bytes.Buffer
		if err := csiTmpl.Execute(&csiBuf, csiData); err != nil {
			return fmt.Errorf("execute CSI template: %w", err)
		}
		if err := r.ensureAddon(ctx, clusterName, "csi", "csi-deployment-"+clusterName, csiCMName, "Reconcile", csiBuf.String()); err != nil {
			return err
		}
	} else if err := r.removeAddon(ctx, clusterName, "csi", "csi-deployment-"+clusterName, csiCMName); err != nil {
		return err
	}

	// -----------------------------------------------------------------------
	// CNI (container network interface)
	// -----------------------------------------------------------------------
	cniCMName := "cni-manifests-" + clusterName
	switch *addons.CNI {
	case "cilium":
		if err := r.ensureAddon(ctx, clusterName, "cni", "cni-deployment-"+clusterName, cniCMName, "ApplyOnce", cniCiliumManifest); err != nil {
			return err
		}
	default: // "none"
		if err := r.removeAddon(ctx, clusterName, "cni", "cni-deployment-"+clusterName, cniCMName); err != nil {
			return err
		}
	}

	return nil
}

// setCondition updates or adds a condition in the XOCluster's Conditions slice.
// LastTransitionTime is only updated when the condition status changes.
func (r *XOClusterReconciler) setCondition(xoCluster *infrastructurev1beta2.XOCluster, conditionType string, status metav1.ConditionStatus, reason, message string) {
	now := metav1.Now()
	for i, c := range xoCluster.Status.Conditions {
		if c.Type == conditionType {
			// Only update LastTransitionTime when the status actually changes
			if c.Status != status {
				xoCluster.Status.Conditions[i].LastTransitionTime = now
			}
			xoCluster.Status.Conditions[i].Status = status
			xoCluster.Status.Conditions[i].Reason = reason
			xoCluster.Status.Conditions[i].Message = message
			return
		}
	}
	xoCluster.Status.Conditions = append(xoCluster.Status.Conditions, metav1.Condition{
		Type:               conditionType,
		Status:             status,
		Reason:             reason,
		Message:            message,
		LastTransitionTime: now,
	})
}
