apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster
metadata:
  name: ${CLUSTER_NAME}
  namespace: ${NAMESPACE}
spec:
  topology:
    class: vates-rhel-from-scratch
    version: ${KUBERNETES_VERSION}
    controlPlane:
      replicas: ${CONTROL_PLANE_MACHINE_COUNT}
    workers:
      machineDeployments:
        - class: worker-from-scratch
          name: md-0
          replicas: ${WORKER_MACHINE_COUNT}
    variables:
      - name: controlPlaneEndpoint
        value:
          host: ${CP_HOST}
          port: ${CP_PORT}
      - name: vmNamePrefix
        value: ${CLUSTER_NAME}
      - name: use-kubevip
        value:
          enabled: false
