apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster
metadata:
  name: my-cluster
spec:
  topology:
    classRef:
      name: vates-almalinux-prefilled
    version: ""
    variables:
      - name: controlPlaneEndpoint
        value:
          host: ""
          port: 0
          subnet: 0
      - name: vmNamePrefix
        value: ""
      - name: controlPlaneLB
        value: ""
    controlPlane:
      replicas: 3
    workers:
      machineDeployments:
        - class: worker-almalinux-prefilled
          name: worker-md-0
          replicas: 2