apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rhel-xoclustertemplate.yaml
  - from-scratch/rhel-from-scratch-control-plane.yaml
  - from-scratch/rhel-from-scratch-worker.yaml
  - from-scratch/clusterclass-rhel-from-scratch.yaml
  - prefilled/rhel-prefilled-control-plane.yaml
  - prefilled/rhel-prefilled-worker.yaml
  - prefilled/clusterclass-rhel-prefilled.yaml
