apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - almalinux-xoclustertemplate.yaml
  - almalinux-fromscratch/almalinux-fromscratch-control-plane.yaml
  - almalinux-fromscratch/almalinux-fromscratch-worker.yaml
  - almalinux-fromscratch/clusterclass-almalinux-fromscratch.yaml
  - almalinux-prefilled/almalinux-prefilled-control-plane.yaml
  - almalinux-prefilled/almalinux-prefilled-worker.yaml
  - almalinux-prefilled/clusterclass-almalinux-prefilled.yaml
