apiVersion: controlplane.cluster.x-k8s.io/v1beta2
kind: KubeadmControlPlaneTemplate
metadata:
  name: rhel-prefilled-control-plane
spec:
  template:
    spec:
      kubeadmConfigSpec:
        clusterConfiguration:
          apiServer:
            certSANs:
              - localhost
              - 127.0.0.1
        initConfiguration:
          nodeRegistration:
            kubeletExtraArgs:
              - name: cgroup-driver
                value: systemd
              - name: cloud-provider
                value: external
        joinConfiguration:
          nodeRegistration:
            kubeletExtraArgs:
              - name: cgroup-driver
                value: systemd
              - name: cloud-provider
                value: external
        preKubeadmCommands:
          - |
            IP=$(hostname -I | awk '{print $1}')
            hostnamectl set-hostname "cp-${IP//./-}"
        postKubeadmCommands:
          - "true"
      machineTemplate:
        metadata:
          labels: {}
