apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-vates
  name: talos-bootstrap-control-plane
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vates-capi-manager-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: cacppt-system
- kind: ServiceAccount
  name: default
  namespace: cabpt-system